folio-org/edge-dcb

src/main/resources/swagger.api/edge-dcb.yaml
Add needed required flag in edge-dcb.yaml file.
While it's helpful for reviewers to help …
=> [UXPROD-4408] - Fixed edge-dcb.yaml file

pom.xml, src/main/java/org/folio/ed/client/DcbClient.java, src/main/java/org/folio/ed/controller/DcbTransactionController.java, src/main/java/org/folio/ed/service/DcbTransactionService.java, src/main/resources/swagger.api/edge-dcb.yaml, src/main/resources/swagger.api/schemas/dcbItem.yaml, src/main/resources/swagger.api/schemas/dcbPatron.yaml, src/main/resources/swagger.api/schemas/dcbTransaction.yaml, src/main/resources/swagger.api/schemas/error.json, src/main/resources/swagger.api/schemas/errors.json, src/main/resources/swagger.api/schemas/metadata.json, src/main/resources/swagger.api/schemas/parameter.json, src/main/resources/swagger.api/schemas/parameters.json, src/main/resources/swagger.api/schemas/role.yaml, src/main/resources/swagger.api/schemas/transactionStatusResponse.yaml, src/test/java/org/folio/ed/controller/DcbEdgeRequestHandlingTest.java, src/test/java/org/folio/ed/service/DcbTransactionServiceTest.java, src/test/java/org/folio/ed/utils/EntityUtils.java
[EDGEDCB-2](https://issues.folio.org/browse/EDGEDCB-2)
While it's helpful for reviewers to …
=> [EDGEDCB-2]-implemented dcb endpoints

src/main/resources/swagger.api/edge-dcb.yaml, src/main/resources/swagger.api/schemas/dcbItem.yaml, src/main/resources/swagger.api/schemas/dcbPatron.yaml, src/main/resources/swagger.api/schemas/dcbPickup.yaml, src/main/resources/swagger.api/schemas/dcbTransaction.yaml, src/test/java/org/folio/ed/utils/EntityUtils.java
EDGEDCB-3 Refactoring of yaml files and include pickup related objects
While it's helpful …
=> EDGEDCB-3 Refactoring of yaml files and include pickup related objects

src/main/resources/swagger.api/schemas/dcbItem.yaml
https://issues.folio.org/browse/EDGEDCB-4
remove loanType from Item object in edge-dcb module
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
=> EDGEDCB-4: remove loanType from Item object in edge-dcb module

README.md, src/main/resources/application.yml
=> EDGEDCB-11 Adding new properties required for secure store

src/main/java/org/folio/ed/controller/ExceptionHandlingController.java, src/test/java/org/folio/ed/controller/DcbEdgeRequestHandlingTest.java
=> EDGEDCB-14 400 error code should be thrown for Invalid UUID

pom.xml
Updated the version of pom.
While it's helpful for reviewers to help identify potential …
=> FOLIO-3968 - Updated pom version.

descriptors/ModuleDescriptor-template.json, pom.xml
Change the dependency name
While it's helpful for reviewers to help identify potential …
=> Folio 3968 - Updated dependency name.

README.md
The purpose of this PR is to mention about test tenant details in ephemeral.properties file in readme file which can be referred by devops team to configure it correctly to make karate runs execution for edge-dcb module.
Added details in readme file.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the …
=> EDGEDCB-15 - Adding details about test tenant to make karate features run

README.md
Removed underscore character for the test tenant created for edge-dcb karate testing.
While …
=> EDGEDCB-16 - Tenant ID test_edge_dcb should not contain underscore.

README.md
The purpose of the PR is to implement EDGEDCB-19
Adding the required permission for the user in the readme file
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
=> EDGEDCB-19 Add required permission in readme.md file

MODULE_SELF_EVALUATION.md
Added self evaluation md file for TC process.
While it's helpful for reviewers to help …
=> [TCR-35] - Added MODULE_SELF_EVALUATION.md file.

README.md, pom.xml, src/main/resources/application.yml, src/test/java/org/folio/ed/controller/DcbEdgeRequestHandlingTest.java
The purpose of the PR is to implement EDGEDCB-17
After upgrading the dependency of edge-common-spring, test cases were failing as the mock were written for older version. After changing the mock, everything started to pass.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
=> EDGEDCB-17 upgrading dependencies for Quesnelia

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml
=> [EDGEDCB-18]-Q release 1.1.0

README.md, pom.xml, src/main/java/org/folio/ed/client/DcbClient.java, src/main/java/org/folio/ed/controller/DcbTransactionController.java, src/main/java/org/folio/ed/service/DcbTransactionService.java, src/main/resources/swagger.api/edge-dcb.yaml, src/main/resources/swagger.api/schemas/transactionStatusResponse.yaml, src/test/java/org/folio/ed/controller/DcbEdgeRequestHandlingTest.java, src/test/java/org/folio/ed/service/DcbTransactionServiceTest.java
The purpose of the PR is to implement [EDGEDCB-20](https://folio-org.atlassian.net/browse/EDGEDCB-20)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
=> EDGEDCB-20 Implement GET API for transaction updates

pom.xml
=> EDGEDCB-23 - Update version in pom file.

NEWS.md, pom.xml, src/main/java/org/folio/ed/EdgeDcbApplication.java
=> To release 1.1.2

NEWS.md, pom.xml
=> To release 1.1.3

pom.xml
=> EDGEDCB-30 Update pom.xml dependencies for ramsons

NEWS.md, pom.xml
=> Ramsons release

NEWS.md, pom.xml
=> T0 release 1.2.1

NEWS.md, pom.xml
=> Post release 1.2.1

src/main/java/org/folio/ed/client/DcbClient.java, src/main/java/org/folio/ed/controller/DcbTransactionController.java, src/main/java/org/folio/ed/service/DcbTransactionService.java, src/main/resources/swagger.api/edge-dcb.yaml, src/main/resources/swagger.api/schemas/dcbUpdateItem.yaml, src/main/resources/swagger.api/schemas/dcbUpdateTransaction.yaml, src/test/java/org/folio/ed/controller/DcbEdgeRequestHandlingTest.java, src/test/java/org/folio/ed/service/DcbTransactionServiceTest.java, src/test/java/org/folio/ed/utils/EntityUtils.java
[EDGEDCB-34](https://folio-org.atlassian.net/browse/EDGEDCB-34)
=> EDGEDCB-34 Add the edge API for DCB re-request

NEWS.md, pom.xml, src/main/java/org/folio/ed/client/DcbClient.java, src/main/java/org/folio/ed/controller/DcbTransactionController.java, src/main/java/org/folio/ed/service/DcbTransactionService.java, src/main/resources/swagger.api/edge-dcb.yaml, src/main/resources/swagger.api/schemas/dcbUpdateItem.yaml, src/main/resources/swagger.api/schemas/dcbUpdateTransaction.yaml, src/test/java/org/folio/ed/controller/DcbEdgeRequestHandlingTest.java, src/test/java/org/folio/ed/service/DcbTransactionServiceTest.java, src/test/java/org/folio/ed/utils/EntityUtils.java
=> To release 1.2.2

src/main/java/org/folio/ed/client/DcbClient.java, src/main/java/org/folio/ed/controller/DcbTransactionController.java, src/main/java/org/folio/ed/service/DcbTransactionService.java, src/main/resources/swagger.api/edge-dcb.yaml, src/main/resources/swagger.api/schemas/dcbUpdateItem.yaml, src/main/resources/swagger.api/schemas/dcbUpdateTransaction.yaml, src/test/java/org/folio/ed/controller/DcbEdgeRequestHandlingTest.java, src/test/java/org/folio/ed/service/DcbTransactionServiceTest.java, src/test/java/org/folio/ed/utils/EntityUtils.java
=> Merge code changes for EDGEDCB-34

src/main/resources/swagger.api/schemas/dcbItem.yaml
https://folio-org.atlassian.net/browse/EDGEDCB-45
While it's helpful for reviewers to help …
=> EDGEDCB-45: added renewalPolicy fields in dcbItem.yaml

src/main/java/org/folio/ed/client/DcbClient.java, src/main/java/org/folio/ed/controller/DcbTransactionController.java, src/main/java/org/folio/ed/service/DcbTransactionService.java, src/main/resources/swagger.api/edge-dcb.yaml, src/test/java/org/folio/ed/controller/DcbEdgeRequestHandlingTest.java, src/test/java/org/folio/ed/service/DcbTransactionServiceTest.java, src/test/java/org/folio/ed/utils/EntityUtils.java
[EDGEDCB-41](https://folio-org.atlassian.net/browse/EDGEDCB-41)
=> EDGEDCB-41 Create PUT /transaction/{dcbTransactionId}/renew API to allow the DCB hub to perform the renew operation

.dockerignore, Dockerfile, Jenkinsfile, pom.xml, src/main/resources/application.yml, src/test/java/org/folio/ed/controller/DcbEdgeRequestHandlingTest.java, src/test/resources/application-test.yaml
=> FOLIO-4228 - Java 21 and spring version upgrade

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml
=> Update versions and NEWS.md file

NEWS.md, pom.xml, src/main/java/org/folio/ed/client/DcbClient.java, src/main/java/org/folio/ed/controller/DcbTransactionController.java, src/main/java/org/folio/ed/service/DcbTransactionService.java, src/main/resources/swagger.api/edge-dcb.yaml, src/main/resources/swagger.api/schemas/dcbItem.yaml, src/test/java/org/folio/ed/controller/DcbEdgeRequestHandlingTest.java, src/test/java/org/folio/ed/service/DcbTransactionServiceTest.java, src/test/java/org/folio/ed/utils/EntityUtils.java
=> To release 1.2.3

NEWS.md, pom.xml, src/main/java/org/folio/ed/client/DcbClient.java, src/main/java/org/folio/ed/controller/DcbTransactionController.java, src/main/java/org/folio/ed/service/DcbTransactionService.java, src/main/resources/swagger.api/edge-dcb.yaml, src/main/resources/swagger.api/schemas/dcbItem.yaml, src/test/java/org/folio/ed/controller/DcbEdgeRequestHandlingTest.java, src/test/java/org/folio/ed/service/DcbTransactionServiceTest.java, src/test/java/org/folio/ed/utils/EntityUtils.java
=> To release 1.1.6

NEWS.md, pom.xml, src/main/resources/swagger.api/schemas/dcbTransaction.yaml
Ramsons R2 2024
https://folio-org.atlassian.net/browse/EDGEDCB-55
While it's helpful for …
=> Ramsons release 1.2.4

.github/PULL_REQUEST_TEMPLATE.md, .github/dependabot.yml, CODEOWNERS
- to have in place the process for automation of the updates of dependent modules
- to have standardized approach for all the Pull Requests created for the modules of volaris team
- for codeowners been automatically tagged in PRs
- add `dependabot.yml` config file
- add `PULL_REQUEST_TEMPLATE.md` file
- add `CODEOWNERS` file
[EDGEDCB-51](https://folio-org.atlassian.net/browse/EDGEDCB-51)
- …
=> EDGEDCB-51: Add config file for dependabot, code owners and template for pull request
